# Test Notebook

In [ ]:
import numpy as np
from geomechy.io import jsonReader
from geomechy.core import NodeSet, ElementSet, ShapeFunctionsManager, ConstitutiveManager, GroupSet
from geomechy.base import Properties
from geomechy.materials import Soil
from geomechy.core import MaterialSet

## Load Json Data

In [ ]:
jsonFile = "./assets/json/template.json"
data = jsonReader(jsonFile)
data.keys()

dict_keys(['Nodes', 'Elements', 'Groups', 'Materials', 'Physics', 'Constitutive', 'FEM', 'Solver', 'Modules', 'Writers'])

In [ ]:
nodes = NodeSet()
nodes.readFromDict(data)
nodes

{1: array([0.    , 3.6576]),
 2: array([0., 0.]),
 3: array([3.048 , 0.3048]),
 4: array([3.048 , 3.6576]),
 5: array([6.096 , 0.6096]),
 6: array([6.096 , 3.6576])}

In [ ]:
nodes.getNodeCoords(1)

array([0.    , 3.6576])

In [ ]:
elems = ElementSet()
elems.readFromDict(data)
elems

{1: [[1, 2, 3, 4],
  <6x4 sparse matrix of type '<class 'numpy.float64'>'
  	with 4 stored elements in COOrdinate format>],
 2: [[3, 4, 5, 6],
  <6x4 sparse matrix of type '<class 'numpy.float64'>'
  	with 4 stored elements in COOrdinate format>]}

In [ ]:
groups = GroupSet(data["Groups"])
groups

{'NodeGroups': [{'BC1': {'name': 'Boundary_14', 'nodes': [1, 4]},
   'BC2': {'name': 'Boundary_65', 'nodes': [6, 5]}}],
 'ElementGroups': [{'ALL': {'name': 'All_Domain', 'elements': [1, 2]}}]}

In [ ]:
shape = ShapeFunctionsManager(nodes, elems)
shape.getShapeFunc()
shape.getShapeData(1)

{'gp': array([[-0.5774, -0.5774],
        [ 0.5774, -0.5774],
        [-0.5774,  0.5774],
        [ 0.5774,  0.5774]]),
 'we': array([[1.],
        [1.],
        [1.],
        [1.]]),
 'N': [array([0.622 , 0.1667, 0.0447, 0.1667]),
  array([0.1667, 0.622 , 0.1667, 0.0447]),
  array([0.1667, 0.0447, 0.1667, 0.622 ]),
  array([0.0447, 0.1667, 0.622 , 0.1667])],
 'dN': [array([[-0.3943,  0.3943,  0.1057, -0.1057],
         [-0.3943, -0.1057,  0.1057,  0.3943]]),
  array([[-0.3943,  0.3943,  0.1057, -0.1057],
         [-0.1057, -0.3943,  0.3943,  0.1057]]),
  array([[-0.1057,  0.1057,  0.3943, -0.3943],
         [-0.3943, -0.1057,  0.1057,  0.3943]]),
  array([[-0.1057,  0.1057,  0.3943, -0.3943],
         [-0.1057, -0.3943,  0.3943,  0.1057]])]}

In [ ]:
mat = data["Materials"]
props = MaterialSet(mat)
props

{'Water': <geomechy.materials.Water at 0x29f98c289b0>,
 'Clay': <geomechy.materials.Soil at 0x29f98c28d30>}

In [ ]:
props["Clay"].name

'Clay'

In [ ]:
constitutive = ConstitutiveManager(data["Constitutive"])
constitutive[0].getElasticMatrix()

KeyError: 0