# Test Notebook

In [ ]:
import numpy as np
from geomechy.io import jsonReader
from geomechy.core import NodeSet, ElementSet, ShapeFunctionsManager, ConstitutiveManager, GroupSet
from geomechy.base import Properties
from geomechy.materials import Soil
from geomechy.core import MaterialSet

## Load Json Data

In [ ]:
jsonFile = "./assets/json/template.json"
data = jsonReader(jsonFile)
data.keys()

dict_keys(['Nodes', 'Elements', 'Groups', 'Materials', 'Physics', 'Constitutive', 'FEM', 'Solver', 'Modules', 'Writers'])

In [ ]:
nodes = NodeSet()
nodes.readFromDict(data)
nodes

{1: array([0.    , 3.6576]),
 2: array([0., 0.]),
 3: array([3.048 , 0.3048]),
 4: array([3.048 , 3.6576]),
 5: array([6.096 , 0.6096]),
 6: array([6.096 , 3.6576])}

In [ ]:
nodes.numNodes

6

In [ ]:
elems = ElementSet()
elems.readFromDict(data)
elems

{1: {'Nodes': [1, 2, 3, 4],
  'Le': <6x4 sparse matrix of type '<class 'numpy.float64'>'
  	with 4 stored elements in Compressed Sparse Row format>},
 2: {'Nodes': [3, 4, 5, 6],
  'Le': <6x4 sparse matrix of type '<class 'numpy.float64'>'
  	with 4 stored elements in Compressed Sparse Row format>}}

In [ ]:
groups = GroupSet(data["Groups"])
groups["ElementGroups"]
# for item in groups["ElementGroups"]:
#     if 1 in list(item.values())[0]["elements"]:
#         print("si esta")

[{'ALL': {'name': 'All_Domain',
   'elements': [1, 2],
   'materials': ['Water', 'Clay']}}]

In [ ]:
mat = data["Materials"]
props = MaterialSet(mat)
props

{'Water': <geomechy.materials.Water at 0x22685cdc5c0>,
 'Clay': <geomechy.materials.Soil at 0x22685cdc588>}

In [ ]:
shape = ShapeFunctionsManager(nodes, elems)
shape.getShapeFunc()
shape

{1: {'gp': array([[-0.5774, -0.5774],
         [ 0.5774, -0.5774],
         [-0.5774,  0.5774],
         [ 0.5774,  0.5774]]),
  'we': array([[1.],
         [1.],
         [1.],
         [1.]]),
  'N': [array([0.622 , 0.1667, 0.0447, 0.1667]),
   array([0.1667, 0.622 , 0.1667, 0.0447]),
   array([0.1667, 0.0447, 0.1667, 0.622 ]),
   array([0.0447, 0.1667, 0.622 , 0.1667])],
  'dN': [array([[-0.3943,  0.3943,  0.1057, -0.1057],
          [-0.3943, -0.1057,  0.1057,  0.3943]]),
   array([[-0.3943,  0.3943,  0.1057, -0.1057],
          [-0.1057, -0.3943,  0.3943,  0.1057]]),
   array([[-0.1057,  0.1057,  0.3943, -0.3943],
          [-0.3943, -0.1057,  0.1057,  0.3943]]),
   array([[-0.1057,  0.1057,  0.3943, -0.3943],
          [-0.1057, -0.3943,  0.3943,  0.1057]])]},
 2: {'gp': array([[-0.5774, -0.5774],
         [ 0.5774, -0.5774],
         [-0.5774,  0.5774],
         [ 0.5774,  0.5774]]),
  'we': array([[1.],
         [1.],
         [1.],
         [1.]]),
  'N': [array([0.622 , 0.166

In [ ]:
constitutive = ConstitutiveManager(data["Constitutive"])
constitutive

{'Clay': <geomechy.constitutive.PlaneStrain at 0x22685cdc518>}